# Homebrew formula for Fendix — hybrid API and code security scanner.
#
# Tap and install:
#   brew tap Abdel-RahmanSaied/fendix
#   brew install fendix
#
# This file is auto-regenerated by the engine repo's release.yml on
# every `v*` tag. Hand-edits here will be overwritten on the next
# release; edit the canonical copy in the engine repo instead.

class Fendix < Formula
  desc "Hybrid API and code security scanner"
  homepage "https://github.com/Abdel-RahmanSaied/homebrew-fendix"
  license "MIT"
  version "3.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-arm64"
      sha256 "ed4710301a6d38e43f3e8efcfd269c772d82e64e2cd34786128890d624226626"
    else
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-darwin-amd64"
      sha256 "e406a891e82dbdb0debcb6977ae59f4d82a97b8b2f4718d7a13567e7a7fc97b6"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-linux-arm64"
      sha256 "53a48dd6ab231699eb961d8e551bb52d4abc7b3a8944c563e80a3a0abc2a64c0"
    else
      url "https://github.com/Abdel-RahmanSaied/homebrew-fendix/releases/download/v#{version}/fendix-v#{version}-linux-amd64"
      sha256 "b0fc0063b3d59e87f57c102bcf614f3852e528fcf3cec6efce5e5ee016f7bbb6"
    end
  end

  depends_on "python@3.11" => :recommended

  def install
    bin.install Dir["fendix-*"].first => "fendix"
  end

  def caveats
    <<~EOC
      Fendix includes an embedded Python engine for whitebox analysis.
      For best results, ensure Python 3 is installed:
        brew install python@3.11

      Quick start:
        fendix scan --url https://api.example.com
        fendix scan --code ./src --spec openapi.yaml --format html -o report.html
    EOC
  end

  test do
    assert_match "fendix version", shell_output("#{bin}/fendix version")
  end
end
