# Homebrew formula for Fendix — hybrid API and code security scanner.
#
# Tap and install:
#   brew tap Fendix-app/fendix
#   brew install fendix
#
# This file is auto-regenerated by the engine repo's release.yml on
# every `v*` tag. Hand-edits here will be overwritten on the next
# release; edit the canonical copy in the engine repo instead.

class Fendix < Formula
  desc "Application security scanner with evidence-backed release decisions"
  homepage "https://fendix.dev"
  license "MIT"
  version_scheme 1

  depends_on "python@3.11" => :recommended

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.6.0/fendix-v3.6.0-darwin-arm64"
      sha256 "66c6a0787b397bbe52d260c1bca18fd736cdee65f7fa1df0aa99729911fb6818"
    else
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.6.0/fendix-v3.6.0-darwin-amd64"
      sha256 "e9102d7da58ddc310c4fd106e4943e0357cf9ed7fc018900ebcfdd7915584cc1"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.6.0/fendix-v3.6.0-linux-arm64"
      sha256 "1d17b3ff4a14f9b74dc31c92a00f60f472c96fd112bb3a6740b32879a68f4894"
    else
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.6.0/fendix-v3.6.0-linux-amd64"
      sha256 "c5d7b047087115acffeb65a523ebcfc76f6ac2e8b5728f89ac77b573b7899ff4"
    end
  end

  def install
    bin.install Dir["fendix-*"].first => "fendix"
  end

  def caveats
    <<~EOC
      This formula installs the standalone Go binary and recommends a Python
      interpreter, but it does not install the Fendix Python analyzer tree.
      --code auto-enables that phase; without a version-matched tree through
      FENDIX_ENGINE or an engine pin, the phase is recorded as skipped while
      native analyzers continue. Use the official container or a source
      checkout for ready-to-run hybrid coverage.

      Quick start:
        fendix scan --url https://api.example.com
        fendix scan --code ./src --python-engine=false --format html -o report.html
    EOC
  end

  test do
    assert_match "fendix version", shell_output("#{bin}/fendix version")
  end
end
