# Homebrew formula for Fendix — hybrid API and code security scanner.
#
# Tap and install:
#   brew tap Fendix-app/fendix
#   brew install fendix
#
# This file is auto-regenerated by the engine repo's release.yml on
# every `v*` tag. Hand-edits here will be overwritten on the next
# release; edit the canonical copy in the engine repo instead.

class Fendix < Formula
  desc "Application security scanner with evidence-backed release decisions"
  homepage "https://fendix.dev"
  license "MIT"

  depends_on "python@3.11" => :recommended

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.4.1/fendix-v3.4.1-darwin-arm64"
      sha256 "8813891266600867465cae1fc60a1934768452d7c19354615c74d83e12e4eecd"
    else
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.4.1/fendix-v3.4.1-darwin-amd64"
      sha256 "4540178a1a25609403bbc9cf326c097f4d404a56cf32a15dd092f011b96c84bb"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.4.1/fendix-v3.4.1-linux-arm64"
      sha256 "85930244fc3af97870853f14d104164fdc52b61acf67d033ce643c8595278489"
    else
      url "https://github.com/Fendix-app/Fendix/releases/download/v3.4.1/fendix-v3.4.1-linux-amd64"
      sha256 "668b07d69ed0b9a2e30416dff75a77b203e6adb0b550b3e6cb6d8f8a2416a767"
    end
  end

  def install
    bin.install Dir["fendix-*"].first => "fendix"
  end

  def caveats
    <<~EOC
      The default scanner is a single Go binary. Python 3.11 is installed as a
      recommended dependency for the optional --python-engine analysis path.

      Quick start:
        fendix scan --url https://api.example.com
        fendix scan --code ./src --spec openapi.yaml --format html -o report.html
    EOC
  end

  test do
    assert_match "fendix version", shell_output("#{bin}/fendix version")
  end
end
